alias: "{{ automation_alias }}"
mode: single
trigger:
  - platform: state
    entity_id: "{{ trigger_entity }}"
action:
  - service: rest_command.test_system_cleanup_base
  - service: rest_command.test_system_cleanup_hausie
  - service: rest_command.test_system_create_base
  - service: rest_command.test_system_create_hausie
